version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: ./src/BlogCore.Hosts.Web.Server/Dockerfile